### ISSUE TITLE
Cant apply bleed damage to ghouls 

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [Fin-bar/Pf2e-Alignment-Damage#1]
![image](https://user-images.githubusercontent.com/62528192/218516394-707f6913-6026-486b-b04e-b22a5970ce95.png)
error message created for persistant damage on ghouls.

**Comment by Fin-bar** [comment]
The linked error message is for an unrelated module. Ghouls, as nonliving creatures, are immune to bleed damage: https://2e.aonprd.com/Rules.aspx?ID=340
