### ISSUE TITLE
Suggestion: Option for non-opposed alignments to do half damage

### ISSUE THREAD

**Issue by zacdemon** [Fin-bar/Pf2e-Alignment-Damage#2]
Pretty much title. It would be nice if there was an option for alignments that are not directly opposed to deal half damage instead. Ex. a NE creature takes full good damage and half chaotic and lawful damage. 

Don't know how hard this would be to implement.

**Comment by zagaroth** [comment]
Alternatively, to keep in the style of resistance PF2E uses, they have a resistance of 2x their level? 

I'm not sure I'd use this option, but if I was going to, this version would be more consistent with current rules.

**Comment by ChasarooniZ** [comment]
Would also appreciate either of, or both of these approaches ^

**Comment by Fin-bar** [comment]
Implemented as [minimum level-based resistance](https://2e.aonprd.com/Rules.aspx?ID=1014).
