### ISSUE TITLE
Request: Incorporeality house-rules

### ISSUE THREAD

**Issue by zagaroth** [Fin-bar/Pf2e-Alignment-Damage#3]
Hello, I have a simple-in-concept request regarding incorporeality and alignment/mental damage:

Two checkboxes. One turns off resistances for alignment damage, the other turns off mental damage resistance. 

The idea came up in my group's Saturday game, and is discussed on this [Reddit thread](https://www.reddit.com/r/Pathfinder2e/comments/11izmga/thoughts_on_alignment_damage_and_incorporeality/), where it seems a fairly popular idea. 

If you decide not to do it, please let me know and I will take a crack at it as my first Foundry mod, but a smaller mod list seems better if you feel it fits with what you want to do.

**Comment by Fin-bar** [comment]
Unlike some traits that actually have specific rules about damage types, such as undead not taking bleed damage or constructs not taking mental damage, the [Incorporeal Trait](https://2e.aonprd.com/Traits.aspx?ID=222) does not actually provide those immunities; they are instead found on the specific monsters. As such, this would be a data entry task, not a damage calculation task, and I am not planning to do that at this time.

**Comment by zagaroth** [comment]
Yeah, after looking at it, that doesn't work. 

A universal macro doesn't work, it would have to check for an incorporeal trait on everything in the compendium and then edit the resistance, and would need to be run after every update.

A single-target macro could work, but at that point, you aren't saving a lot of effort over doing it manually. Unless your game has a lot of incorporeal creatures. :)
