### ISSUE TITLE
Bug: 'Apply all alignment damage as spirit damage' interferes with Healing

### ISSUE THREAD

**Issue by TangledLion** [Fin-bar/Pf2e-Alignment-Damage#4]
Under the Alignment Damage Susceptibility options the 'Apply all alignment damage as spirit damage' being the active behavior makes the "Heal" button on damage cards not apply health to the selected token when clicked. This doesn't happen with "Replace with spirit damage on roll" option however.

**Comment by Fin-bar** [comment]
I think I saw this issue and then totally forgot about it instead of doing anything about it 😅 Fixed in the latest release!
