### ISSUE TITLE
Persistent bleed in constructs

### ISSUE THREAD

**Issue by LeandroMartinelli** [Fin-bar/Pf2e-Alignment-Damage#5]
Hi!!
When a set the persistent bleed options to All Creatures I have a problem...
For Undead it's ok  but the Constructs are still immune to bleed.

Thank you for the greate work!!

**Comment by Fin-bar** [comment]
Many construct creatures are *explicitly* immune to bleed, rather than just inheriting it from the construct trait. Removing that immunity from the creature will let the module behave as expected.
